### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'deny_new'

### ISSUE THREAD

**Issue by wulavi** [Kr4ken-9/DAB#72] opened 2020-07-22 04:14 UTC
Here we are with another issue. Today, after trying to open my main.py, this issue comes up (I've never gotten it before). Is there any way to fix it? I have already deleted the pips and the file and re-downloaded them but the same issue comes up. Please let me know if you know how to fix it. Thanks.
![image](https://user-images.githubusercontent.com/68147160/88133522-7c947780-cc0c-11ea-9c9d-62ff699a4c17.png)

**Comment by Kr4ken-9** [comment] 2020-07-22 16:47
I've experienced this issue too. I believe it's caused by an outdated version of discord.py, which means it can be fixed very easily. I will probably fix it later today.

**Comment by Kr4ken-9** [comment] 2020-07-22 18:10
This should be fixed in https://github.com/Kr4ken-9/DAB/commit/f2316764f3aaa10ae0f14a4811d70d0d33abd132, just git pull and reinstall requirements.txt

**Comment by wulavi** [comment] 2020-07-23 01:51
Awesome, I will try it out later. Thank you!

**Comment by wulavi** [comment] 2020-07-23 02:55
It works, thank you again!

**Closed** 2020-07-23 02:55 UTC
